--- #YAML:1.0
name:                Makefile-Parallel
version:             0.03
abstract:            A distributed parallel makefile
license:             ~
author:              
    - Ruben Fonseca <root@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Clone:                         0.2
    Date::Parse:                   2.27
    Digest::MD5:                   2.36
    GraphViz:                      2.02
    Log::Log4perl:                 1.07
    Parse::Yapp::Driver:           1.05
    Proc::Reliable:                1.16
    Proc::Simple:                  1.21
    Test::More:                    0.63
    Text::Balanced:                2
    Time::HiRes:                   1.55
    Time::Interval:                1.2
    Time::Piece::ISO:              0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
