--- #YAML:1.0
name:               Makefile-Parallel
version:            0.07
abstract:           A distributed parallel makefile
author:
    - Ruben Fonseca <root@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Clone:                0.20
    Date::Parse:          2.27
    Digest::MD5:          2.36
    GraphViz:             2.02
    Log::Log4perl:        1.07
    Parse::Yapp::Driver:  1.05
    Proc::Reliable:       1.16
    Proc::Simple:         1.21
    Test::More:           0.63
    Text::Balanced:       2.0.0
    Time::HiRes:          1.550
    Time::Interval:       1.2
    Time::Piece::ISO:     0.10
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
