--- #YAML:1.0
name:                Makefile-Parallel
version:             0.02
abstract:            A distributed parallel makefile
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Clone:                         0.2
    Date::Parse:                   2.27
    Digest::MD5:                   2.36
    GraphViz:                      2.02
    Log::Log4perl:                 1.07
    Parse::Yapp:                   0
    Proc::Reliable:                1.16
    Proc::Simple:                  1.21
    Test::More:                    0.63
    Text::Balanced:                0
    Time::HiRes:                   1.55
    Time::Interval:                1.2
    Time::Piece::ISO:              0.1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ruben Fonseca <root@cpan.org>
